---
- hosts: webserver
  vars:
  - app_name: awesome_project
  - projects_repository: https://github.com/penguinjournals/ansible-101-website.git
  - local_temporary_storage_folder: /tmp
  - remote_temporary_storage_folder: /tmp

  vars_files:
  - vault.yml

  tasks:
  - name: download version locally to get configuration files
    tags: local_download
    local_action:
      module: git repo={{ projects_repository }} dest={{ local_temporary_storage_folder }}/{{ app_name }}

  - name: empty destination folder
    sudo: yes
    file: path=/var/www/html state=absent

  - name: download application to destination server
    tags: remote_download
    sudo: yes
    git: repo={{ projects_repository }} dest=/var/www/html/

  - name: rewrite configuration file
    tags: regenerate_configuration_file
    sudo: yes
    template: src={{ local_temporary_storage_folder }}/{{ app_name }}/credentials.php dest=/var/www/html/credentials.php
