---
- hosts: all

  tasks:
  - name: Install base common packages
    become: yes
    apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - git

- hosts: frontends

  tasks:
  - name: Install frontend base packages
    become: yes
    apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
    with_items:
       - git
       - memcached
       - apache2
       - libapache2-mod-php5
  
  - name: Delete default index file
    become: yes
    file:
        path=/var/www/html/index.html state=absent

  - name: Copy index file
    become: yes
    template:
      src=index.php
      dest=/var/www/html/


- hosts: databases

  tasks:
  - name: Install database base packages
    become: yes
    apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
    with_items:
       - git
       - redis-server
