---
- hosts: all

  tasks:
  - name: Install base common packages
    sudo: yes
    apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - git

- hosts: frontends

  tasks:
  - name: Install frontend base packages
    sudo: yes
    apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
    with_items:
  
  - name: Delete default index file
    sudo: yes
    file:

  - name: Copy index file
    sudo: yes
    template:


- hosts: databases

  tasks:
  - name: Install database base packages
