---
- hosts: all

  tasks:
  - name: Install base common packages
    sudo: yes
    apt: name={{item}} update_cache=yes state=present
    with_items:
      - git

- hosts: frontends

  tasks:
  - name: Install frontend base packages
    sudo: yes
    apt: name={{item}} update_cache=yes state=present
    with_items: 
      - apache2
      - libapache2-mod-php5
      - memcached
  - name: Delete default index file
    sudo: yes
    file: path=/var/www/html/index.html state=absent
  - name: Copy index file
    sudo: yes
    template: src=index.php dest=/var/www/html/index.php 


- hosts: databases

  tasks:
  - name: Install database base packages
    sudo: yes
    apt: name={{item}} update_cache=yes state=present
    with_items:
      - redis-server
