---
# tasks file for common
- name: Install base software common to all nodes
  sudo: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - htop
    - vim
