- hosts: tag_Role_Frontend
  serial: 1
  vars_files:
    - vault.yml
  tasks:
    - name: Gathering ec2 facts
      tags: gather_facts
      action: ec2_facts
    - name: Instance De-register
      tags: deregister
      local_action:
        module: ec2_elb
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: eu-west-1
        instance_id: "{{ ansible_ec2_instance_id }}"
        state: absent
    - name: Copy index file
      sudo: yes
      template: src=index.html dest=/var/www/html/index.html
    - name: Instance Register
      tags: register
      local_action:
        module: ec2_elb
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: eu-west-1
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ item }}"
        state: present
      with_items: ec2_elbs
