---
- name: Upload Config | tomcat7 | standard
  template:
    src: etc/tomcat7/server.xml
    dest: /etc/tomcat7/server.xml
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0644
  notify: Restart Service | tomcat7
  tags:
    - tomcat

- name: Configure | tomcat7 | change logging dir
  lineinfile:
    dest: "/etc/tomcat7/logging.properties"
    regexp: "^1catalina.org.apache.juli.FileHandler.directory"
    line: "1catalina.org.apache.juli.FileHandler.directory = {{ tomcat_log_root }}"
    state: present
  notify: Restart Service | tomcat7
  tags:
    - tomcat

- name: Start Service | tomcat7
  service:
    name: tomcat7
    state: started
    enabled: yes
  when: tomcat_enabled
  tags:
    - tomcat
